#!/usr/bin/env bash
set -Eeuo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-}"
REPOSITORY="https://api.github.com/repos/Xhiveee/goodgames/tarball"
APP_DIR="/opt/goodgames"
HTTP_PORT="18081"
WEB_PORT="18080"

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

[[ "$EUID" -eq 0 ]] || fail "Run with sudo or as root."
[[ "$DOMAIN" =~ ^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(\.([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?))+$ ]] || fail "Pass valid domain as first argument."
[[ "$EMAIL" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] || fail "Pass valid email as second argument."

if [[ ! -f /etc/debian_version ]]; then
  fail "Installer supports Debian and Ubuntu."
fi

command -v systemctl >/dev/null 2>&1 || fail "systemd is required."

if ! command -v nginx >/dev/null 2>&1; then
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y nginx
fi

command -v nginx >/dev/null 2>&1 || fail "nginx installation failed."

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin is required."

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y certbot curl ca-certificates
systemctl enable --now docker
NGINX_AVAILABLE="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled/goodgames-${DOMAIN}.conf"
NGINX_SITE="${NGINX_AVAILABLE}/goodgames-${DOMAIN}.conf"
if [[ ! -d "$NGINX_AVAILABLE" || ! -d /etc/nginx/sites-enabled ]]; then
  fail "Expected nginx sites-available and sites-enabled directories. Install Debian's nginx package."
fi

if command -v ss >/dev/null 2>&1; then
  for port in 18081 8443; do
    if ss -ltn "sport = :${port}" 2>/dev/null | grep -q LISTEN; then
      fail "Port ${port} is already in use. Identify its owner with 'ss -ltnp | grep :${port}' and free the port before deployment."
    fi
  done
fi

if [[ -e "$NGINX_ENABLED" && ! -L "$NGINX_ENABLED" ]]; then
  fail "${NGINX_ENABLED} exists and is not a symlink; inspect it before deployment."
fi
if [[ -L "$NGINX_ENABLED" && "$(readlink -f "$NGINX_ENABLED")" != "$(readlink -m "$NGINX_SITE")" ]]; then
  fail "${NGINX_ENABLED} points to another nginx site; inspect it before deployment."
fi
if [[ -e "$NGINX_SITE" ]] && ! grep -qF '# Managed by goodgames-deploy.' "$NGINX_SITE"; then
  fail "${NGINX_SITE} exists and is not managed by this installer."
fi

while IFS= read -r existing_file; do
  [[ "$existing_file" == "$NGINX_ENABLED" ]] && continue
  [[ "$existing_file" == "$NGINX_SITE" ]] && continue
  if ! grep -qF '# Managed by goodgames-deploy.' "$existing_file"; then
    fail "Domain ${DOMAIN} already appears in ${existing_file}; resolve nginx conflict first."
  fi
done < <(grep -RIlF -- "$DOMAIN" /etc/nginx/sites-enabled /etc/nginx/conf.d 2>/dev/null || true)

temporary_dir="$(mktemp -d)"
trap 'rm -rf "$temporary_dir"' EXIT
curl -fsSL "$REPOSITORY" -o "${temporary_dir}/source.tar.gz"
mkdir -p "$APP_DIR"
tar -xzf "${temporary_dir}/source.tar.gz" --strip-components=1 -C "$APP_DIR"

cat > "${APP_DIR}/.env" <<EOF
VITE_SLITHER_SERVER_URL=wss://${DOMAIN}/slither
EOF
chmod 600 "${APP_DIR}/.env"
docker compose -f "${APP_DIR}/compose.yaml" -p goodgames up -d --build

mkdir -p /var/www/certbot
write_http_config() {
  cat > "$NGINX_SITE" <<EOF
# Managed by goodgames-deploy. Do not edit this file manually.
server {
    listen ${HTTP_PORT};
    server_name ${DOMAIN};
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files \$uri =404;
    }
    location / {
        proxy_pass http://127.0.0.1:${WEB_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
}

ln -sfn "$NGINX_SITE" "$NGINX_ENABLED"
if [[ -s "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" && -s "/etc/letsencrypt/live/${DOMAIN}/privkey.pem" ]]; then
  sed "s/__DOMAIN__/${DOMAIN}/g" "${APP_DIR}/deploy/nginx-host.conf.template" > "$NGINX_SITE"
else
  write_http_config
fi
nginx -t
if systemctl is-active --quiet nginx; then
  systemctl reload nginx
else
  systemctl enable --now nginx || fail "Could not start nginx. Check 'systemctl status nginx' and 'journalctl -xeu nginx'."
fi

certbot certonly --webroot -w /var/www/certbot -d "$DOMAIN" \
  --email "$EMAIL" --agree-tos --non-interactive --keep-until-expiring \
  --http-01-port "$HTTP_PORT" --http-01-address 0.0.0.0

sed "s/__DOMAIN__/${DOMAIN}/g" "${APP_DIR}/deploy/nginx-host.conf.template" > "$NGINX_SITE"
nginx -t
systemctl reload nginx

mkdir -p /etc/letsencrypt/renewal-hooks/deploy
cat > /etc/letsencrypt/renewal-hooks/deploy/reload-goodgames-nginx.sh <<'EOF'
#!/usr/bin/env sh
systemctl reload nginx
EOF
chmod 755 /etc/letsencrypt/renewal-hooks/deploy/reload-goodgames-nginx.sh
systemctl enable --now certbot.timer

printf 'Deployment complete: https://%s\n' "$DOMAIN"
printf 'Renewal schedule: certbot.timer\n'
